language: python
python:
  - "2.7"

install: "pip install -r requirements.txt"

before_script:
  - autopep8 -ir *
  - flake8 --max-complexity=12 --exclude=*.txt,*.md --max-line-length=200 *

script:
  - cd UnitTest
  - python TestTennis.py -v
  - coverage run --branch TestTennis.py
  - coverage report -m
